type Props = {
    heading: string;
    description: string;
    description2: string;
    description3: string;
    description4: string;
    description5: string;
  };
  
  export type Layout135Props = React.ComponentPropsWithoutRef<"section"> & Partial<Props>;
  
  export const Layout135 = (props: Layout135Props) => {
    const { heading, description, description2, description3, description4, description5 } = {
      ...Layout135Defaults,
      ...props,
    } as Props;
    return (
      <section id="relume" className="px-[5%] py-16 md:py-24 lg:py-28">
        <div className="container max-w-lg">
          <h3 className="text-4xl font-bold leading-[1.2] md:text-5xl lg:text-6xl text-center">{heading}</h3>
          <p className="mt-5 md:mt-6 md:text-md">{description}</p>
          <p className="mt-5 md:mt-6 md:text-md">{description2}</p>
          <p className="mt-5 md:mt-6 md:text-md">{description3}</p>
          <p className="mt-5 md:mt-6 md:text-md">{description4}</p>
          <p className="mt-5 md:mt-6 md:text-md">{description5}</p>

        </div>
      </section>
    );
  };
  
  export const Layout135Defaults: Layout135Props = {
    heading: "Powerful Insights",
    description:
      "92.96% of global traffic is generated by Google Search, Google Images, and Google Maps",
      description2:"60% of consumers avoid businesses with a rating lower than 3.5 stars",
      description3:"88% of buyers check ratings before making a decision",
      description4:"Positive reviews can increase sales by 31%",
      description5:"Online reviews influence 93% of consumer purchase decisions",
  };
  