"use client";

import { useRef } from "react";
import { useMediaQuery } from "@relume_io/relume-ui";
import { MotionValue, motion, useScroll, useTransform } from "framer-motion";
import React from "react";

type ImageProps = {
  src: string;
  alt?: string;
};

type FeatureSectionProps = {
  icon: ImageProps;
  title: string;
  description: string;
  number: string;
};

type Props = {
  heading: string;
  featureSections: FeatureSectionProps[];
};

export type Layout417Props = React.ComponentPropsWithoutRef<"section"> & Partial<Props>;

export const Layout417 = (props: Layout417Props) => {
  const { heading, featureSections } = {
    ...Layout417Defaults,
    ...props,
  } as Props;

  const containerRef = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({
    target: containerRef,
  });

  return (
    <section ref={containerRef} id="case">
      <div className="container relative h-[300svh] lg:h-[300vh]">
        <div className="sticky top-0 grid h-[100svh] grid-cols-1 content-center items-center justify-center px-[5%] md:flex md:content-normal md:px-0 lg:h-screen">
          <div className="absolute bottom-auto left-0 right-0 top-0 flex w-full justify-center overflow-hidden pt-20 md:inset-auto md:pt-0">
            <h1 className="whitespace-nowrap text-9xl font-bold sm:text-[5.5rem] md:text-[7.5rem] lg:text-[10rem] text-yellow-400">
              {heading}
            </h1>
          </div>
          <div className="sticky top-0 mx-auto mt-12 flex min-h-[24.5rem] w-full max-w-sm flex-col items-center justify-center sm:mt-24 md:relative lg:mt-0">
            {featureSections.map((section, index) => (
              <FeatureSection
                key={index}
                section={section}
                index={index}
                totalSections={featureSections.length}
                scrollYProgress={scrollYProgress}
              />
            ))}
          </div>
        </div>
      </div>
      <div className="absolute inset-0 -z-10 mt-[100vh]" />
    </section>
  );
};

const FeatureSection = ({
  section,
  index,
  totalSections,
  scrollYProgress,
}: {
  section: FeatureSectionProps;
  index: number;
  totalSections: number;
  scrollYProgress: MotionValue<number>;
}) => {
  const isMobile = useMediaQuery("(max-width: 767px)");

  const sectionScrollStart = index / totalSections;
  const sectionScrollEnd = (index + 1) / totalSections;

  const rotate = useTransform(
    scrollYProgress,
    [sectionScrollStart, sectionScrollEnd],
    [0 + index * 3, -10],
  );
  const translateY = useTransform(
    scrollYProgress,
    [sectionScrollStart, sectionScrollEnd],
    ["0vh", "-120vh"],
  );

  return (
    <motion.div
      className="absolute mx-6 flex flex-col justify-between border border-border-primary bg-background-primary p-8 md:mx-0"
      style={{
        rotate: isMobile && index === totalSections - 1 ? "9deg" : rotate,
        translateY: isMobile && index === totalSections - 1 ? undefined : translateY,
        zIndex: `${totalSections - index}`,
      }}
    >
      <h3 className="mb-3 text-xl font-bold md:mb-4 md:text-2xl text-yellow-400">{section.title}</h3>
      <p><span className="font-bold">{section.number}</span>{section.description}</p>
    </motion.div>
  );
};

export const Layout417Defaults: Layout417Props = {
  heading: "Case of study",
  featureSections: [
    {
      icon: {
        src: "https://relume-assets.s3.amazonaws.com/relume-icon.svg",
        alt: "Relume logo 1",
      },
      title: "Web traffic",
      number: "92.96%",
      description:
        " of global traffic is generated by Google Search, Google Images, and Google Maps",
    },
    {
      icon: {
        src: "https://relume-assets.s3.amazonaws.com/relume-icon.svg",
        alt: "Relume logo 2",
      },
      number: "60%",
      title: "Lower rating",
      description:
        " of consumers avoid businesses with a rating lower than 3.5 stars",
    },
    {
      icon: {
        src: "https://relume-assets.s3.amazonaws.com/relume-icon.svg",
        alt: "Relume logo 3",
      },
      number: "88%",
      title: " Purchase decision",
      description:
        "of buyers check ratings before making a decision",
    },
    {
      icon: {
        src: "https://relume-assets.s3.amazonaws.com/relume-icon.svg",
        alt: "Relume logo 4",
      },
      number: "31%",
      title: "Sales increase",
      description:
        " of sales increase with positive reviews",
    },
    {
        icon: {
          src: "https://relume-assets.s3.amazonaws.com/relume-icon.svg",
          alt: "Relume logo 3",
        },
        number: "93%",
        title: " Consumer influence",
        description:
          "   of consumers have their purchase decisions influenced by online reviews",
      },
  ],
};
